name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt
        # Instalar explícitamente httpx para las pruebas
        pip install httpx pytest pytest-cov

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with black
      run: |
        black --check .

    - name: Check imports with isort
      run: |
        isort --check-only --profile black .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov httpx

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  build-and-deploy:
    name: Build and Deploy
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'imartinezt/ci-cd'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Configure Docker for GCP'
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: 'Build and Push Image'
      run: |
        # Usar SHA corto del commit para versionar la imagen
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        
        IMAGE_NAME="hello-world-fastapi"
        PROJECT_ID="crp-dev-dig-mlcatalog"
        REGION="us-central1"
        REGISTRY_NAME="cicd"
        TAG_LATEST="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REGISTRY_NAME}/${IMAGE_NAME}:latest"
        TAG_VERSION="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REGISTRY_NAME}/${IMAGE_NAME}:${SHORT_SHA}"
        
        # Construir con el tag específico de versión y latest
        docker buildx build --platform linux/amd64 -t $TAG_VERSION -t $TAG_LATEST .
        
        # Subir ambas etiquetas
        docker push $TAG_VERSION
        docker push $TAG_LATEST
        
        # Guardar tag para usar en el siguiente paso
        echo "IMAGE_TAG=$TAG_VERSION" >> $GITHUB_ENV

    - name: 'Deploy to Cloud Run'
      run: |
        SERVICE_NAME="fastapi-hello-world-service"
        PROJECT_ID="crp-dev-dig-mlcatalog"
        REGION="us-central1"
        
        # Usar la imagen con versión creada en el paso anterior
        gcloud run deploy $SERVICE_NAME \
          --image=${{ env.IMAGE_TAG }} \
          --region=$REGION \
          --platform=managed \
          --port=9819 \
          --cpu=4 \
          --memory=16Gi \
          --min-instances=1 \
          --max-instances=50 \
          --timeout=3600s \
          --concurrency=80 \
          --execution-environment=gen2 \
          --project=$PROJECT_ID \
          --no-allow-unauthenticated
        
        echo "Deployed version ${{ env.IMAGE_TAG }} to $SERVICE_NAME"